### ISSUE TITLE
pip package not installable

### ISSUE THREAD

**Issue by Zeitsperre** [yrobink/SBCK-python#6]
Hey there,

I'm running  into this issue when installing the new package:
```
(test) ➜  ~ pip install sbck   
Collecting sbck
  Using cached SBCK-1.0.2.tar.gz (18 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jk6chfd8/sbck_2866f26b655f4007995096c293095808/setup.py", line 184, in <module>
          with open( os.path.join( here , "SBCK" , "__release.py" ) , "r" ) as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-jk6chfd8/sbck_2866f26b655f4007995096c293095808/SBCK/__release.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It either has to do with some missing files from the package itself or a configuration issue. I'll see if I can pinpoint the problem.

**Comment by yrobink** [comment]
Dear @Zeitsperre,

Thanks for your help, a new version is available on pypi
